export default {
    FIRST_NAME: "FIRST_NAME",
    LAST_NAME: "LAST_NAME",
    EMAIL: "EMAIL",
    PHONE: "PHONE",
    SHIPPING_ADDRESS: "SHIPPING_ADDRESS",
    ZIP_CODE: "ZIP_CODE",
    CREDIT_CARD: "CREDIT_CARD",
    EXPIRATION_MONTH: "EXPIRATION_MONTH",
    EXPIRATION_YEAR: "EXPIRATION_YEAR",
    PASSWORD: "PASSWORD",
    CVV: "CVV",
    PLACE: "PLACE"
}